# Generated by Django 3.2.7 on 2021-09-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
